export const GET_ALL_TALES = "GET_ALL_TALES";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ONE_TALE = "GET_ONE_TALE";
export const GET_ONE_USER_WITH_VOTE = "GET_ONE_USER_WITH_VOTE";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_RATES = "GET_ALL_RATES";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const GET_TALES_PAGINATION = "GET_TALES_PAGINATION";
