import React from 'react'
import type { Metadata } from 'next'

import { SpeedInsights } from '@vercel/speed-insights/next'
import ReactQueryProvider from '@/app/context/ReactQueryProvider'
import AuthProvider from '@/app/context/AuthProvider'
import NextUiProviderComponent from '@/app/context/NextUiProviderComponent'

import './globals.css'

import dynamic from 'next/dynamic'
const Navigation = dynamic(() => import('@/modules/navigation/Navigation'))
const Footer = dynamic(() => import('@/modules/footer'))

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'min-h-[100dvh] flex flex-col'}>
        <NextUiProviderComponent>
          <ReactQueryProvider>
            <AuthProvider>
              <Navigation />
              {children}
            </AuthProvider>
          </ReactQueryProvider>
          <Footer />
        </NextUiProviderComponent>
        <SpeedInsights />
      </body>
    </html>
  )
}
