import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/app/context/AuthProvider'
import NextUiProviderComponent from '@/app/context/NextUiProviderComponent'
import React from 'react'
import dynamic from 'next/dynamic'
import { SpeedInsights } from '@vercel/speed-insights/next'
const Navigation = dynamic(() => import('@/modules/navigation/Navigation'))

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextUiProviderComponent>
          <AuthProvider>
            <Navigation />
            {children}
          </AuthProvider>
        </NextUiProviderComponent>
        <SpeedInsights />
      </body>
    </html>
  )
}
